name: release

on:
  push:
    # 监听 main 分支的 push 事件
    branches:
      - main
# 赋予 release-please-action 权限
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  # 设置 release-please 任务
  release:
    # 设置任务运行环境为 windows-latest
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      # 使用 release-please-action 动作来自动创建发布 PR
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: rust
  build:
    needs: release
    if: needs.release.outputs.release_created == 'true'
    runs-on: windows-latest
    steps:
      # 检出代
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: 构建发布版本
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: wechatv-windows-x64
          path: target/release/wechatv.exe
  
  publish:
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:
      - name: 导入构建产物
        uses: actions/download-artifact@v4
        with:
          name: wechatv-windows-x64
          path: ./

      - name: 压缩文件
        uses: vimtor/action-zip@v1.2
        with:
          files: wechatv.exe
          dest: wechatv-windows-x64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: wechatv-windows-x64.zip
          tag_name: ${{ needs.release-please.outputs.tag_name }}
